services:
  - type: web
    name: ironclad-support-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_APP_TOKEN
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
      - key: IRONCLAD_CHANNEL_ID
        sync: false
